### ISSUE TITLE
URIs DCAT

### ISSUE THREAD

**Issue by mikel-egana-aranguren** [opendata-euskadi/LOD-datasets#4]
Las URIs de los DCAT dan un 503: http://opendata.euskadi.eus/datos/-/retribuciones-altos-cargos-y-personal-eventual-gobierno-vasco-y-organismos-autonomos-y-entes-publicos/

`<dcat:Dataset rdf:about="http://opendata.euskadi.eus/datos/-/retribuciones-altos-cargos-y-personal-eventual-gobierno-vasco-y-organismos-autonomos-y-entes-publicos/">`

**Comment by imanol-argueso** [comment]
En realidad la URI correcta sería <dcat:Dataset rdf:about="http://opendata.euskadi.eus/catalogo/-/retribuciones-altos-cargos-y-personal-eventual-gobierno-vasco-y-organismos-autonomos-y-entes-publicos/">
Deberían ser "/catalogo/" y no "/datos/".

**Comment by mikel-egana-aranguren** [comment]
@imanol-argueso si, eso suponía, pero de 6 datasets que he visitado, los 6 tenían eso mal. Me estoy fijando en eso por que queria usar el DCAT como punto de partida para luego añadirle metadatos (VoID) y provenance (PROV) a cada dataset convertido a RDF, pero con esa URI mal ...

**Comment by SPANIAGU** [comment]
Antiguamente, la misma página tenía el alias datos y luego se añadió el
alias catálogo, de modo que funcionaban ambas.
Parece ser que en algún momento se eliminó el alias de datos de la página y
por eso ahora no funciona.

Imanol, quizás eventualmente ¿puedas volver a añadir ese alias para que
Mikel continúe ? y luego ya vemos cuál dejamos fijo y generamos los
ficheros con uno concreto. Ya que habría que cambiar el código y regenerar
los 3.000 DCATs y publicarlos.

Mikel, otra forma que no se sí es correcta sería acceder para lo que estás
haciendo es acceder a los ficheros RDF-XML que se encuentran publicados
aquí:
http://opendata.euskadi.eus/catalogo/-/catalogo-de-datos/

**Comment by mikel-egana-aranguren** [comment]
@SPANIAGU de momento no lo necesito realmente, voy a meter a mano la URI  "/catalogo/" en mis DCAT locales y con eso me arreglo. Habrá que arreglarlo, pero podemos esperar hasta tener las URIs definitivas para catalogo (Por ejemplo quedamos en quitar el guion de la URI de catalogo, si no recuerdo mal) y regenerara todos los DCAT entonces

**Comment by futuretelematics** [comment]
Corregido, pendiente de subida y de ejecución
... de momento las uris llevan /-/ hasta que se defina la solución definitiva
